import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'fabric-loom'
    id 'maven-publish'
    id "com.modrinth.minotaur"
    id 'net.darkhax.curseforgegradle'
}

version = mod_version
group = mod_group_id
base {
    archivesName = mod_id
}

def changelogText = project.file('changelog.md').text
def site_debugMode = false

repositories {
    maven { url = "https://maven.maxhenkel.de/repository/public" }
    maven { url = "https://api.modrinth.com/maven" }
    mavenCentral()
}


loom {
    runs {
        client {
            client()
            setConfigName('Fabric Client 1.20.1')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
    }
}


dependencies {

    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"

    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    modRuntimeOnly "maven.modrinth:simple-voice-chat:fabric-${voicechat_version}"
    implementation "de.maxhenkel.voicechat:voicechat-api:${project.voicechat_api_version}"

    modCompileOnly("io.wispforest:accessories-fabric:${project.accessories_version}")
    modRuntimeOnly("io.wispforest:accessories-fabric:${project.accessories_version}")

    modImplementation("software.bernie.geckolib:geckolib-fabric-${minecraft_version}:${geckolib_version}")
    implementation("com.eliotlash.mclib:mclib:20")

    modImplementation "io.wispforest:owo-lib:${project.owo_version}"
    include "io.wispforest:owo-sentinel:${project.owo_version}"

    compileOnly "com.electronwill.night-config:toml:3.6.0"

}


processResources {
    def properties = [
            "version"        : project.version,
            "minecraft_version": project.minecraft_version,
            "loader_version" : project.loader_version,
            "voicechat_version": project.voicechat_version,
            "geckolib_version": project.geckolib_version,
            "owo_version": project.owo_version,
            "mod_id"         : project.mod_id,
            "mod_name"       : project.mod_name,
            "mod_license"    : project.mod_license,
            "mod_group_id"   : project.mod_group_id,
            "mod_authors"    : project.mod_authors,
            "mod_description": project.mod_description
    ]

    inputs.properties properties
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") { expand properties }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.mod_group_id}" }
    }
}

tasks.register('curseforge', TaskPublishCurseForge) {
    apiToken = System.getenv("CURSEFORGE_TOKEN")

    def mainFile = upload('1524395', file("build/libs/${mod_id}-${mod_version}.jar"))
    mainFile.displayName = "${mod_name}-${mod_version}"
    mainFile.releaseType = 'beta'
    mainFile.changelog = changelogText
    debugMode = site_debugMode
    mainFile.gameVersions.add("Java 17")
    mainFile.gameVersions.add("Fabric")
    mainFile.gameVersions.add("1.20.1")
    mainFile.gameVersions.add("Server")
    mainFile.gameVersions.add("Client")

    mainFile.addRequirement("simple-voice-chat")
    mainFile.addRequirement("fabric-api")
    mainFile.addRequirement("geckolib")
    mainFile.addRequirement("owo-lib")
    mainFile.addOptional("accessories")

}


modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "immersive-frequencies"
    versionName = "${mod_name}-${mod_version}"
    versionNumber = "${mod_version}"
    versionType = "beta"
    uploadFile = file("build/libs/${mod_id}-${mod_version}.jar")
    gameVersions = ["${minecraft_version}"] as Iterable<? extends String>
    loaders = ["fabric"]
    changelog = changelogText
    debugMode = site_debugMode


    dependencies {
        required.project "fabric-api"
        required.project 'simple-voice-chat'
        required.project 'owo-lib'
        optional.project 'accessories'

    }
}

tasks.register('publicModdedSite') {
    dependsOn 'build'
    dependsOn 'curseforge'
    dependsOn 'modrinth'
}